### PR TITLE
Execution of phing with vagrant failed.

### PR DESCRIPTION
**Pull request by siad007**
At least phpunit and phpmd are not longer supported by pear installation, so the phing build inside vagrant fails. With this changes i got it to work again. btw installing dependencies with composer inside vm would not work, if the host is a windows machine.

### CODE REVIEW

**Comment by davvd** [comment]
@siad007 Thanks, someone will review your pull request soon

**Comment by yegor256** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@siad007 many thanks!

**Comment by davvd** [comment]
@rultor deploy

**Pull request merged**
