### PR TITLE
Added tests for phpRack_Package_Php_Version

### PR DESCRIPTION
**Pull request by Gamesh**

### CODE REVIEW

**Comment by davvd** [comment]
Many thanks for the PR, let me find a reviewer for it

**Comment by Gamesh** [comment]
looks like your travis CI is miss-configured

**Comment by yegor256** [comment]
@Gamesh yeah, I'm going to configure it properly tomorrow and we'll merge your branch. thanks for it btw!

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by yegor256** [comment]
@Gamesh there are merge conflicts. could you please merge master into your branch?

**Comment by Gamesh** [comment]
@yegor256 sure i'll do it in the evening

**Comment by Gamesh** [comment]
hmm, i see you moved the source files and test files inside src, i'll move mine there too

**Comment by Gamesh** [comment]
I resolved merge conflicts. I also added bootstrap.php into src/tests folder because i couldn't run tests from any folder without setting include path for unit tests it also now works straight from netbeans IDE should also work in phpstorm. And added ext-com_dotnet to composer requirements as it's required by CPU Package that COM class is present. In PHP 5.6 it's no longer bundled in the zip

**Comment by Gamesh** [comment]
looks like build failed, could be because of the added requirement ext-com_dotnet, i'll remove it for now

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by Gamesh** [comment]
looks like something wrong with phpcs

**Comment by yegor256** [comment]
@Gamesh well, it's a valid complaint. you should rename properties in `PhpTest`

**Comment by Gamesh** [comment]
OK, I'll fix that. I don't really like underscores in private properties or methods and PSR-4 discourages them too. But for the project consistent naming convention sake I'll add it ;)

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by Gamesh** [comment]
finally :) would be nice to have an autoloader instead of bunch require_once

**Comment by yegor256** [comment]
@Gamesh you're always welcome to fix it :)

**Comment by Gamesh** [comment]
i'll look in to that :) composer autoloader could be used, but that would require php 5.3 at least, and current project requirements are 5.2

**Comment by yegor256** [comment]
@Gamesh we can upgrade to 5.3, I think. 5.2 is rather old version anyway

**Comment by Gamesh** [comment]
then it should be easy, I'll set up composer's autoloader for tests and other files. Will send you a pull request this week

**Comment by davvd** [comment]
@rultor deploy

**Pull request merged**
